server:
  port: 9999
#设置实体所在的包，然后在mapper.xml里面不用写实体的全名，直接写实体的以小写字母开头的简单类名即可,例如：com.tracker.entity.User,可以直接写user
mybatis:
  mapper-locations: com.example.managerment.repository.mapper/*Mapper.xml
  type-aliases-package: com.example.xnlogin.mess
  configuration:
    mapUnderscoreToCamelCase: true

spring:
  datasource: #jdbc:oracle:thin:@192.168.21.244:1521:orcl
    url: jdbc:oracle:thin:@192.168.21.244:1521:orcl?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    username: platform
    password: platform
    driverClassName: oracle.jdbc.driver.OracleDriver